
name: nanortax
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - conda-forge::python
  - conda-forge::markdown
  - conda-forge::pymdown-extensions
  - conda-forge::pygments
  - anaconda::scikit-bio
  - bioconda::csvtk
  - bioconda::taxonkit
  - fastp
  - kraken2
  - centrifuge
  - pandas
  - blast
  - gawk
